question_data = [
    {
        "category": "Politics",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Who was the only president to not be in office in Washington D.C?",
        "correct_answer": "George Washington",
        "incorrect_answers": ["Abraham Lincoln", "Richard Nixon", "Thomas Jefferson"]
    },
    {
        "category": "Politics",
        "type": "multiple", "difficulty": "medium",
        "question": "Who was the 40th President of the USA?",
        "correct_answer": "Ronald Reagan",
        "incorrect_answers": ["Jimmy Carter", "Bill Clinton", "Richard Nixon"]
    },
    {
        "category": "Politics",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Who became Prime Minister of the United Kingdom in July 2016?",
        "correct_answer": "Theresa May",
        "incorrect_answers": ["Boris Johnson", "David Cameron", "Tony Blair"]
    },
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
                                                  "question": "In United States history, how many vice presidents did Franklin D. Roosevelt have during his time in office as president?",
                                                  "correct_answer": "3", "incorrect_answers": ["1", "2", "0"]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
                                                  "question": "Who succeeded Joseph Stalin as General Secretary of the Communist Party of the Soviet Union?",
                                                  "correct_answer": "Nikita Khrushchev",
                                                  "incorrect_answers": ["Leonid Brezhnev", "Mikhail Gorbachev",
                                                                        "Boris Yeltsin"]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
                                                  "question": "What was the personal nickname of the 40th Governor of the US State Louisiana, Huey Long?",
                                                  "correct_answer": "The Kingfish",
                                                  "incorrect_answers": ["The Champ", "The Hoot Owl", "The Oracle"]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
                                                  "question": "Which former US president used &quot;Let&#039;s Make America Great Again&quot; as his campaign slogan before Donald Trump&#039;s campaign?",
                                                  "correct_answer": "Ronald Reagan",
                                                  "incorrect_answers": ["Jimmy Carter", "Gerald Ford",
                                                                        "Richard Nixon"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
                                                  "question": "Jeb Bush was elected as Governor of Florida in 2002, starting his political career.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
                                                  "question": "What year did Gerald Ford Become President?",
                                                  "correct_answer": "1974",
                                                  "incorrect_answers": ["1977", "1973", "1969"]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
                                                  "question": "What are the first names of the first father and son pair that were both Prime Ministers of Canada?",
                                                  "correct_answer": "Justin and Pierre",
                                                  "incorrect_answers": ["John and Louis", "Brian and Justin",
                                                                        "Brian and Pierre"]}
]

